export const ROUTES = {
  HOME: '/',
  EXPLAINER: '/explainer',
  FEATURES: '/features',
  CONTACT: '/contact',
  COMING_SOON: '/coming-soon',
  AUTH: '/auth',
  DASHBOARD: '/dashboard',
  BLOG: '/blog',
  BLOG_POST: '/blog/:slug',
  VC_DIRECTORY: '/vc',
  VC_PROFILE: '/vc/:slug',
  GLOSSARY: '/glossary',
  GLOSSARY_TERM: '/glossary/:slug',
} as const;
