export const ROUTES = {
  HOME: '/',
  EXPLAINER: '/explainer',
  FEATURES: '/features',
  CONTACT: '/contact',
  COMING_SOON: '/coming-soon',
  AUTH: '/auth',
  DASHBOARD: '/dashboard',
  BLOG: '/blog',
  BLOG_POST: '/blog/:slug',
  VC_DIRECTORY: '/vc',
  VC_PROFILE: '/vc/:slug',
  GLOSSARY: '/glossary',
  GLOSSARY_TERM: '/glossary/:slug',
  PRIVACY: '/privacy-policy',
  TERMS: '/terms-of-service',
  AUTH_ACTION: '/auth/action',
} as const;

export const DASHBOARD_ROUTES = {
  OVERVIEW: '/dashboard',
  UPLOAD: '/dashboard/upload',
  SCOREBOARD: '/dashboard/scoreboard',
  PIPELINE: '/dashboard/pipeline',
  PORTFOLIO: '/dashboard/portfolio',
  MARKET: '/dashboard/market',
  MARKET_STARTUP: '/dashboard/market/startup/:id',
  USERS: '/dashboard/users',
  CONNECTORS: '/dashboard/connectors',
  SETTINGS: '/dashboard/settings',
  BILLING: '/dashboard/billing',
} as const;
